# Generated by Django 2.2.27 on 2022-03-28 08:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2022, 3, 28, 11, 52, 51, 449576), verbose_name='Опубликована'),
        ),
    ]
